// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkqchkocmmzybrbljedh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrcWNoa29jbW16eWJyYmxqZWRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNjQxOTYsImV4cCI6MjA3MTc0MDE5Nn0.GiUBuN6Cp0As2WYXrOUF1Yr516ZYVUA6mWJq3-YMw_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});